name: "GELOS"
description: "Grupo de Extensão em Livre & Open Source - ICMC USP"
url: "https://gelos.club"

sass:
  style: compact

source: src

permalink: /:path/:basename/

exclude:
  - "README.md"
  - "*/README.md"

collections:
  # Notícias para o público num geral
  posts:
    output: true
    permalink: /:year/:month/:day/:title:output_ext
    name: Notícias
  # Relatórios de reuniões
  meetings:
    output: true
    permalink: /reunioes/:year-:month-:day:output_ext
    name: Reuniões
  # Informações sobre projetos/atividades contínuas
  projects:
    output: true
    permalink: /projetos/:title:output_ext
    name: Projetos
  # Conteúdo perene de knowledge base
  wiki:
    output: true
    permalink: /wiki/:title:output_ext
    name: Wiki
  # Páginas pessoais dos membros
  members:
    output: true
    permalink: /membros/:title/
    name: Membros

defaults:
  -
    scope:
      type: posts
    values:
      show_date: true
      layout: article
      parent: /blog/
  -
    scope:
      type: meetings
    values:
      pdf: true
      show_date: true
      layout: article
      parent: /reunioes/
  -
    scope:
      type: projects
    values:
      layout: article
      parent: /projetos/
  -
    scope:
      type: wiki
    values:
      layout: article
      parent: /wiki/
  -
    scope:
      type: members
    values:
      layout: member
      parent: /membros/
  -
    scope:
      path: "api"
    values:
      layout: none
  -
    scope:
      path: "assets"
    values:
      layout: none
  -
    scope:
      path: ""
    values:
      layout: default
