name: "GELOS"
description: "Grupo de Extensão em Livre & Open Source - ICMC USP"
url: "https://gelos.club"

sass:
  style: compact

source: src

permalink: /:path/:basename/

exclude:
  - "README.md"
  - "*/README.md"

collections:
  # Notícias para o público num geral
  posts:
    output: true
    permalink: /:year/:month/:day/:title:output_ext
    name: Notícias
  # Relatórios de reuniões
  meetings:
    output: true
    permalink: /:year/:month/:day/:title:output_ext
    name: Reuniões
  # Informações sobre projetos/atividades contínuas
  projects:
    output: true
    permalink: /projetos/:title:output_ext
    name: Projetos

defaults:
  -
    scope:
      type: posts
    values:
      layout: post
      parent: /blog/
  -
    scope:
      type: meetings
    values:
      layout: meeting
      parent: /reunioes/
  -
    scope:
      type: projects
    values:
      layout: project
      parent: /projetos/
  -
    scope:
      path: "api"
    values:
      layout: none
  -
    scope:
      path: "assets"
    values:
      layout: none
  -
    scope:
      path: ""
    values:
      layout: default
