# Essa action triggereia o bump-lock.yml do repositório de infra
# Atualizando o flake, gerando um commit, e então criando um deploy
name: "Deploy"
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Autenticar bot
      uses: tibdex/github-app-token@v1
      id: generate-token
      with:
        app_id: 251209
        private_key: ${{ secrets.GELOS_BOT_KEY }}
    - name: Obter URL do PR
      id: get_pr
      continue-on-error: true
      run: |
        echo "url=$(gh api repos/gelos-icmc/site/commits/${{ github.sha }}/pulls | jq '.[0].url' -re)" >> "$GITHUB_OUTPUT"
      env:
        GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
    - name: Sinalizar update
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: bump-lock.yml
        repo: gelos-icmc/infra
        inputs: '{ "name": "gelos-site", "ref": "github:gelos-icmc/site/${{ github.sha }}", "context": "${{ steps.get_pr.outputs.url }}" }'
        token: ${{ steps.generate-token.outputs.token }}
